name: Lint HTML & CSS

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
        working-directory: ../
      - name: Grant execution permission for htmlhint
        run: chmod +x ./node_modules/.bin/htmlhint
        working-directory: ../
      - run: npm run lint:html
        working-directory: ../
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN_LAFLEUR_SONAR }}
